version: '3.8'

services:
  mysqldb:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  backend:
    depends_on:
      - mysqldb
    build: ./twitterb
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    volumes:
      - "./twitterb:/twitterb"
    stdin_open: true
    tty: true
  frontend:
    build:
      context: ./twitterf
    depends_on:
      - backend
    env_file: ./.env
    ports:
      - 3000:3000
    volumes: 
      - "./twitterf:/twitter_f"
      - "/twitter_f/node_modules"
volumes:
  db: