const tweets = [
  {
    id: 0,
    author: 1,
    created: new Date().getTime(),
    message: "This is my first tweet, hi everyone",
    likes: 3,
    retweets: 0,
    comments: 0,
    attach: "/images/phattach.jpeg",
    poll: false,
    pollSettings: {},
  },
  {
    id: 1,
    author: 1,
    created: new Date().getTime(),
    message: "This is my second tweet lol getting good at this",
    likes: 3,
    retweets: 0,
    comments: 0,
    attach: "",
    poll: false,
    pollSettings: {},
  },
  {
    id: 2,
    author: 1,
    created: new Date().getTime(),
    message: "Ok it is getting harder now",
    likes: 3,
    retweets: 0,
    comments: 0,
    attach: "",
    poll: false,
    pollSettings: {},
  },
  {
    id: 3,
    author: 1,
    created: new Date().getTime(),
    message: "Hate the character limit, anyone with me?",
    likes: 3,
    retweets: 0,
    comments: 0,
    attach: "",
    poll: false,
    pollSettings: {},
  },
  {
    id: 4,
    author: 1,
    created: new Date().getTime(),
    message: "How do you win at this",
    likes: 3,
    retweets: 0,
    comments: 0,
    attach: "",
    poll: true,
    pollSettings: {
      choices: ["Yes I do", "No I don't"],
      pollLen: {
        days: 1,
        hours: 3,
        minutes: 35,
      },
      votes: [1, 5],
    },
  },
];

export default tweets;
